title: guesst
description: guesst is a trans/agender multigenre multimedia artist.
url: "https://guesst.net"  # Your site's URL
baseurl: ""

# Build settings
markdown: kramdown  # Markdown processor
theme: minima  # Theme to use

# Plugins
plugins:
  - jekyll-feed  # For RSS feed
  - jekyll-seo-tag  # For SEO tags

# Other settings
permalink: pretty  # Permalink style
exclude: [Gemfile, Gemfile.lock, README.md]  # Files to exclude from the build